import brandEmblem from '../../assets/icons/intro-emblem.png';
import tankArtillery from '../../assets/iconography/artwork/tank-artillery-512.png';
import neonRacer from '../../assets/iconography/artwork/neon-racer-512.png';
import starSwarm from '../../assets/iconography/artwork/star-swarm-512.png';
import brickBlitz from '../../assets/iconography/artwork/brick-blitz-512.png';
import neonSnake from '../../assets/iconography/artwork/neon-snake-512.png';
import posterTank from '../../assets/generated/posters/web/tank-artillery.jpg';
import posterRacer from '../../assets/generated/posters/web/neon-racer.jpg';
import posterSwarm from '../../assets/generated/posters/web/star-swarm.jpg';
import posterBricks from '../../assets/generated/posters/web/brick-blitz.jpg';
import posterSnake from '../../assets/generated/posters/web/neon-snake.jpg';

// AI-generated artwork (see assets/iconography/README.md and
// assets/generated/prompts/) keyed by game id, for cabinets, posters and pages.
export const BRAND_EMBLEM = brandEmblem;

export const EMBLEMS = {
    'tank-artillery': tankArtillery,
    'neon-racer': neonRacer,
    'star-swarm': starSwarm,
    'brick-blitz': brickBlitz,
    'neon-snake': neonSnake,
};

// Wall poster paintings (masters in assets/generated/posters/, generated by
// Codex from the briefs in assets/generated/prompts/; the app loads the
// smaller web copies).
export const POSTERS = {
    'tank-artillery': posterTank,
    'neon-racer': posterRacer,
    'star-swarm': posterSwarm,
    'brick-blitz': posterBricks,
    'neon-snake': posterSnake,
};

const cache = new Map();

// Resolves with a decoded image, or rejects if it can't load. Cached per URL.
export function loadImage(url) {
    if (!cache.has(url)) {
        cache.set(url, new Promise((resolve, reject) => {
            const img = new Image();
            img.onload = () => resolve(img);
            img.onerror = () => reject(new Error(`Image failed to load: ${url}`));
            img.src = url;
        }));
    }
    return cache.get(url);
}
